local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("font", "EmityPlay", [[Interface\Addons\EmityCore\font\EmityPlay.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)

LSM:Register("statusbar", "EmityFlat", [[Interface\Addons\EmityCore\statusbar\EmityFlat.tga]])
LSM:Register("statusbar", "EmityDown", [[Interface\Addons\EmityCore\statusbar\EmityDown.png]])
LSM:Register("statusbar", "EmityUP", [[Interface\Addons\EmityCore\statusbar\EmityUP.png]])
LSM:Register("statusbar", "EmityLeft", [[Interface\Addons\EmityCore\statusbar\EmityLeft.tga]])
LSM:Register("statusbar", "EmityRight", [[Interface\Addons\EmityCore\statusbar\EmityRight.tga]])

LSM:Register("sound", "|cFFff7c0aE - Армия 1", [[Interface\Addons\EmityCore\sound\E - Army 1.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Армия 2", [[Interface\Addons\EmityCore\sound\E - Army 2.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Барабан удар 1", [[Interface\Addons\EmityCore\sound\E - Drum Hit 1.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Барабан удар 2", [[Interface\Addons\EmityCore\sound\E - Drum Hit 2.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Барабан удар 3", [[Interface\Addons\EmityCore\sound\E - Drum Hit 3.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Барабан удар глухой 1", [[Interface\Addons\EmityCore\sound\E - Drum hit dull 1.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Барабан удар глухой 2", [[Interface\Addons\EmityCore\sound\E - Drum hit dull 1.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Бонус 1", [[Interface\Addons\EmityCore\sound\E - Bonus 1.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Бонус 2", [[Interface\Addons\EmityCore\sound\E - Bonus 2.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Бонус 3", [[Interface\Addons\EmityCore\sound\E - Bonus 3.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Бонус 4", [[Interface\Addons\EmityCore\sound\E - Bonus 4.ogg]])
LSM:Register("sound", "|cFFff7c0aE - Бонус 5", [[Interface\Addons\EmityCore\sound\E - Bonus 5.ogg]])
LSM:Register("sound", "|cFFff7c0aE - Быстрый свист", [[Interface\Addons\EmityCore\sound\E - Fast whistle.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Гитара", [[Interface\Addons\EmityCore\sound\E - Guitar.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Гудок", [[Interface\Addons\EmityCore\sound\E - Bike Horn.ogg]])
LSM:Register("sound", "|cFFc41e3bE - Звон", [[Interface\Addons\EmityCore\sound\E - Ring.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Звонкий барабан", [[Interface\Addons\EmityCore\sound\E - Ringing Drum.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Капля", [[Interface\Addons\EmityCore\sound\E - Drop.ogg]])
LSM:Register("sound", "|cFFff7c0aE - Космос", [[Interface\Addons\EmityCore\sound\E - Space.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Ксилофон", [[Interface\Addons\EmityCore\sound\E - Xylophone.ogg]])
LSM:Register("sound", "|cFFff7c0aE - Лазер 1", [[Interface\Addons\EmityCore\sound\E - Laser 1.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Лазер 2", [[Interface\Addons\EmityCore\sound\E - Laser 2.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Лазер 3", [[Interface\Addons\EmityCore\sound\E - Laser 3.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Метал", [[Interface\Addons\EmityCore\sound\E - Metal.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Меч", [[Interface\Addons\EmityCore\sound\E - Sword.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Ошибка 1", [[Interface\Addons\EmityCore\sound\E - Error 1.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Ошибка 2", [[Interface\Addons\EmityCore\sound\E - Error 2.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Поп 1", [[Interface\Addons\EmityCore\sound\E - Pop 1.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Поп 2", [[Interface\Addons\EmityCore\sound\E - Pop 2.mp3]])
LSM:Register("sound", "|cFFc41e3bE - Поп 3", [[Interface\Addons\EmityCore\sound\E - Pop 3.ogg]])
LSM:Register("sound", "|cFFc41e3bE - Пружина 1", [[Interface\Addons\EmityCore\sound\E - Spring 1.ogg]])
LSM:Register("sound", "|cFFc41e3bE - Пружина 2", [[Interface\Addons\EmityCore\sound\E - Spring 2.ogg]])
LSM:Register("sound", "|cFFff7c0aE - Пружина 3", [[Interface\Addons\EmityCore\sound\E - Spring 3.ogg]])
LSM:Register("sound", "|cFFff7c0aE - Робот 1", [[Interface\Addons\EmityCore\sound\E - Robot 1.ogg]])
LSM:Register("sound", "|cFFff7c0aE - Робот 2", [[Interface\Addons\EmityCore\sound\E - Robot 2.ogg]])
LSM:Register("sound", "|cFFff7c0aE - Робот 3", [[Interface\Addons\EmityCore\sound\E - Robot 3.mp3]])
LSM:Register("sound", "|cFFc41e3bE - Рог 1", [[Interface\Addons\EmityCore\sound\E - Horn 1.ogg]])
LSM:Register("sound", "|cFFc41e3bE - Рог 2", [[Interface\Addons\EmityCore\sound\E - Horn 2.mp3]])
LSM:Register("sound", "|cFFc41e3bE - Сонар", [[Interface\Addons\EmityCore\sound\E - Sonar.mp3]])
LSM:Register("sound", "|cFFc41e3bE - Стекло 1", [[Interface\Addons\EmityCore\sound\E - Glass 1.mp3]])
LSM:Register("sound", "|cFFc41e3bE - Стекло 2", [[Interface\Addons\EmityCore\sound\E - Glass 2.mp3]])
LSM:Register("sound", "|cFFc41e3bE - Стекло 3", [[Interface\Addons\EmityCore\sound\E - Glass 3.ogg]])
LSM:Register("sound", "|cFFff7c0aE - Тарелка", [[Interface\Addons\EmityCore\sound\E - Plate.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Телефон", [[Interface\Addons\EmityCore\sound\E - Phone.ogg]])
LSM:Register("sound", "|cFFff7c0aE - Уведомление 1", [[Interface\Addons\EmityCore\sound\E - Notice 1.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Уведомление 2", [[Interface\Addons\EmityCore\sound\E - Notice 2.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Уведомление 3", [[Interface\Addons\EmityCore\sound\E - Notice 3.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Уведомление 4", [[Interface\Addons\EmityCore\sound\E - Notice 4.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Уведомление 5", [[Interface\Addons\EmityCore\sound\E - Notice 5.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Укус", [[Interface\Addons\EmityCore\sound\E - Bite.mp3]])
LSM:Register("sound", "|cFFff7c0aE - Щелчок", [[Interface\Addons\EmityCore\sound\E - Click.ogg]])
LSM:Register("sound", "|cFFa2fff9Адды", [[Interface\Addons\EmityCore\sound\Adds.mp3]])
LSM:Register("sound", "|cFFa2fff9АдскийКлинок", [[Interface\Addons\EmityCore\sound\HellBlade.mp3]])
LSM:Register("sound", "|cFFa2fff9АоеПоРейдуЧерезТриДваОдин", [[Interface\Addons\EmityCore\sound\ChogalAoECount.mp3]])
LSM:Register("sound", "|cFFa2fff9Армагедон", [[Interface\Addons\EmityCore\sound\MagmawArmagedon.mp3]])
LSM:Register("sound", "|cFFa2fff9БафЗакончился", [[Interface\Addons\EmityCore\sound\SinestraBuffDismiss.mp3]])
LSM:Register("sound", "|cFFa2fff9БегиКТанку", [[Interface\Addons\EmityCore\sound\RunToTank.mp3]])
LSM:Register("sound", "|cFFa2fff9БоссДошелДоЛавы", [[Interface\Addons\EmityCore\sound\BossAtLava.mp3]])
LSM:Register("sound", "|cFFa2fff9БоссОтхилился", [[Interface\Addons\EmityCore\sound\BossHealed.mp3]])
LSM:Register("sound", "|cFFa2fff9БочкаВЛево", [[Interface\Addons\EmityCore\sound\RollLeft.mp3]])
LSM:Register("sound", "|cFFa2fff9БочкаВПраво", [[Interface\Addons\EmityCore\sound\RollRight.mp3]])
LSM:Register("sound", "|cFFa2fff9БуряПрячься", [[Interface\Addons\EmityCore\sound\StormHide.mp3]])
LSM:Register("sound", "|cFFa2fff9Взрыв", [[Interface\Addons\EmityCore\sound\Bang.mp3]])
LSM:Register("sound", "|cFFa2fff9Влево", [[Interface\Addons\EmityCore\sound\ToLeft.mp3]])
LSM:Register("sound", "|cFFa2fff9ВозьмиВоздух", [[Interface\Addons\EmityCore\sound\CouncilGetWind.mp3]])
LSM:Register("sound", "|cFFa2fff9ВозьмиЗемлю", [[Interface\Addons\EmityCore\sound\CouncilGetGround.mp3]])
LSM:Register("sound", "|cFFa2fff9Волна", [[Interface\Addons\EmityCore\sound\Wave.mp3]])
LSM:Register("sound", "|cFFa2fff9Вперед", [[Interface\Addons\EmityCore\sound\Forward.mp3]])
LSM:Register("sound", "|cFFa2fff9Вправо", [[Interface\Addons\EmityCore\sound\ToRight.mp3]])
LSM:Register("sound", "|cFFa2fff9ВстаньСлева", [[Interface\Addons\EmityCore\sound\StayLeft.mp3]])
LSM:Register("sound", "|cFFa2fff9ВстаньСправа", [[Interface\Addons\EmityCore\sound\StayRight.mp3]])
LSM:Register("sound", "|cFFa2fff9ВтораяЖизнь", [[Interface\Addons\EmityCore\sound\SecondLife.mp3]])
LSM:Register("sound", "|cFFa2fff9ВтораяФаза", [[Interface\Addons\EmityCore\sound\SecondPhase.mp3]])
LSM:Register("sound", "|cFFa2fff9ВторойВзрыв", [[Interface\Addons\EmityCore\sound\SecondBang.mp3]])
LSM:Register("sound", "|cFFa2fff9ВторыеТкачи", [[Interface\Addons\EmityCore\sound\SecondSpinners.mp3]])
LSM:Register("sound", "|cFFa2fff9ВыйдиИзРейда", [[Interface\Addons\EmityCore\sound\GoOutFromRaid.mp3]])
LSM:Register("sound", "|cFFa2fff9Выровнялся", [[Interface\Addons\EmityCore\sound\Aligned.mp3]])
LSM:Register("sound", "|cFFa2fff9ГлыбыОсмотрись", [[Interface\Addons\EmityCore\sound\IceTombs.mp3]])
LSM:Register("sound", "|cFFa2fff9Гол", [[Interface\Addons\EmityCore\sound\Goal.mp3]])
LSM:Register("sound", "|cFFa2fff9ГорящиеШары", [[Interface\Addons\EmityCore\sound\FireBalls.mp3]])
LSM:Register("sound", "|cFFa2fff9Готовься", [[Interface\Addons\EmityCore\sound\BeReady.mp3]])
LSM:Register("sound", "|cFFa2fff9ГотовьсяКикатьКаст", [[Interface\Addons\EmityCore\sound\BeReadyToKick.mp3]])
LSM:Register("sound", "|cFFa2fff9ГотовьтесьБежать", [[Interface\Addons\EmityCore\sound\BeReadyToRun.mp3]])
LSM:Register("sound", "|cFFa2fff9Грип", [[Interface\Addons\EmityCore\sound\Grip.mp3]])
LSM:Register("sound", "|cFFa2fff9Двойная", [[Interface\Addons\EmityCore\sound\HimeronDoubleAtack.mp3]])
LSM:Register("sound", "|cFFa2fff9Дебафы", [[Interface\Addons\EmityCore\sound\Debuffs.mp3]])
LSM:Register("sound", "|cFFa2fff9ДискоВечеринкаСТентаклями", [[Interface\Addons\EmityCore\sound\Disco.mp3]])
LSM:Register("sound", "|cFFa2fff9Дыхание", [[Interface\Addons\EmityCore\sound\Breath.mp3]])
LSM:Register("sound", "|cFFa2fff9ДыханиеЧерезТриДваОдин", [[Interface\Addons\EmityCore\sound\BreathCount.mp3]])
LSM:Register("sound", "|cFFa2fff9ЖгучееПламяЧерезТриДваОдин", [[Interface\Addons\EmityCore\sound\AtramedesFlameCount.mp3]])
LSM:Register("sound", "|cFFa2fff9ЖмиКнопку", [[Interface\Addons\EmityCore\sound\PressButton.mp3]])
LSM:Register("sound", "|cFFa2fff9ЗеленаяФаза", [[Interface\Addons\EmityCore\sound\MaloriakGreenPhase.mp3]])
LSM:Register("sound", "|cFFa2fff9ЗеленыйБаф", [[Interface\Addons\EmityCore\sound\GreenBuff.mp3]])
LSM:Register("sound", "|cFFa2fff9Имун", [[Interface\Addons\EmityCore\sound\Imune.mp3]])
LSM:Register("sound", "|cFFa2fff9ИмунНаМобе", [[Interface\Addons\EmityCore\sound\SinestraMobImune.mp3]])
LSM:Register("sound", "|cFFa2fff9ИмунСвитч", [[Interface\Addons\EmityCore\sound\ImuneSwitch.mp3]])
LSM:Register("sound", "|cFFa2fff9Искра", [[Interface\Addons\EmityCore\sound\Spark.mp3]])
LSM:Register("sound", "|cFFa2fff9Искры", [[Interface\Addons\EmityCore\sound\Sparks.mp3]])
LSM:Register("sound", "|cFFa2fff9Кайти", [[Interface\Addons\EmityCore\sound\Kite.mp3]])
LSM:Register("sound", "|cFFa2fff9КайтиСферу", [[Interface\Addons\EmityCore\sound\CoucilKiteSphere.mp3]])
LSM:Register("sound", "|cFFa2fff9Капли", [[Interface\Addons\EmityCore\sound\Drops.mp3]])
LSM:Register("sound", "|cFFa2fff9КаплиЖелтую", [[Interface\Addons\EmityCore\sound\Yellow.mp3]])
LSM:Register("sound", "|cFFa2fff9КаплиЗеленую", [[Interface\Addons\EmityCore\sound\Green.mp3]])
LSM:Register("sound", "|cFFa2fff9КикКаст", [[Interface\Addons\EmityCore\sound\KickCast.mp3]])
LSM:Register("sound", "|cFFa2fff9Клинок", [[Interface\Addons\EmityCore\sound\Blade.mp3]])
LSM:Register("sound", "|cFFa2fff9Копье", [[Interface\Addons\EmityCore\sound\Spear.mp3]])
LSM:Register("sound", "|cFFa2fff9Копья", [[Interface\Addons\EmityCore\sound\IceLance.mp3]])
LSM:Register("sound", "|cFFa2fff9КосомордВЛовушке", [[Interface\Addons\EmityCore\sound\RagefaceTraped.mp3]])
LSM:Register("sound", "|cFFa2fff9КосомордОбновилСтаки", [[Interface\Addons\EmityCore\sound\RagefaceRefreshStacks.mp3]])
LSM:Register("sound", "|cFFa2fff9КраснаяФаза", [[Interface\Addons\EmityCore\sound\MaloriakRedPhase.mp3]])
LSM:Register("sound", "|cFFa2fff9КрасныйБаф", [[Interface\Addons\EmityCore\sound\RedBuff.mp3]])
LSM:Register("sound", "|cFFa2fff9Кристалл", [[Interface\Addons\EmityCore\sound\Crystall.mp3]])
LSM:Register("sound", "|cFFa2fff9Кровь", [[Interface\Addons\EmityCore\sound\Blood.mp3]])
LSM:Register("sound", "|cFFa2fff9КрушащееЛезвие", [[Interface\Addons\EmityCore\sound\CrushingBlade.mp3]])
LSM:Register("sound", "|cFFa2fff9ЛаваУворачивайся", [[Interface\Addons\EmityCore\sound\LavaDodge.mp3]])
LSM:Register("sound", "|cFFa2fff9Лево", [[Interface\Addons\EmityCore\sound\Left.mp3]])
LSM:Register("sound", "|cFFa2fff9ЛедВТебя", [[Interface\Addons\EmityCore\sound\IceOnYou.mp3]])
LSM:Register("sound", "|cFFa2fff9Ловушка", [[Interface\Addons\EmityCore\sound\Trap.mp3]])
LSM:Register("sound", "|cFFa2fff9ЛовушкаНаТебе", [[Interface\Addons\EmityCore\sound\TrapOnYou.mp3]])
LSM:Register("sound", "|cFFa2fff9Лужа", [[Interface\Addons\EmityCore\sound\Pool.mp3]])
LSM:Register("sound", "|cFFa2fff9ЛужаРастет", [[Interface\Addons\EmityCore\sound\OmnitronPoolRaise.mp3]])
LSM:Register("sound", "|cFFa2fff9Лужи", [[Interface\Addons\EmityCore\sound\Pools.mp3]])
LSM:Register("sound", "|cFFa2fff9ЛютогрызВЛовушке", [[Interface\Addons\EmityCore\sound\RiplimbTraped.mp3]])
LSM:Register("sound", "|cFFa2fff9ЛютогрызОбновилСтаки", [[Interface\Addons\EmityCore\sound\RiplimbRefreshStacks.mp3]])
LSM:Register("sound", "|cFFa2fff9Магматрон", [[Interface\Addons\EmityCore\sound\OmnitronMagmatron.mp3]])
LSM:Register("sound", "|cFFa2fff9Метеор", [[Interface\Addons\EmityCore\sound\Meteor.mp3]])
LSM:Register("sound", "|cFFa2fff9МетеорНаТебе", [[Interface\Addons\EmityCore\sound\MeteorOnYou.mp3]])
LSM:Register("sound", "|cFFa2fff9МетеорПадает", [[Interface\Addons\EmityCore\sound\MeteorFalling.mp3]])
LSM:Register("sound", "|cFFa2fff9МетеорПоявился", [[Interface\Addons\EmityCore\sound\MeteorAppear.mp3]])
LSM:Register("sound", "|cFFa2fff9МилиОткидка", [[Interface\Addons\EmityCore\sound\MeleTilt.mp3]])
LSM:Register("sound", "|cFFa2fff9МинусМана", [[Interface\Addons\EmityCore\sound\MinusMana.mp3]])
LSM:Register("sound", "|cFFa2fff9МК", [[Interface\Addons\EmityCore\sound\ChogalMC.mp3]])
LSM:Register("sound", "|cFFa2fff9МногоСтаков", [[Interface\Addons\EmityCore\sound\TooManyStacks.mp3]])
LSM:Register("sound", "|cFFa2fff9Молнии", [[Interface\Addons\EmityCore\sound\Lighting.mp3]])
LSM:Register("sound", "|cFFa2fff9МолнииЧерезТриДваОдин", [[Interface\Addons\EmityCore\sound\NefarianElectrocuteCount.mp3]])
LSM:Register("sound", "|cFFa2fff9МолотВЦентре", [[Interface\Addons\EmityCore\sound\HummerCenter.mp3]])
LSM:Register("sound", "|cFFa2fff9МолотСлева", [[Interface\Addons\EmityCore\sound\HummerLeft.mp3]])
LSM:Register("sound", "|cFFa2fff9МолотСправа", [[Interface\Addons\EmityCore\sound\HummerRight.mp3]])
LSM:Register("sound", "|cFFa2fff9Назад", [[Interface\Addons\EmityCore\sound\Back.mp3]])
LSM:Register("sound", "|cFFa2fff9НаТанкеМногоСтаков", [[Interface\Addons\EmityCore\sound\TankALotOfStacks.mp3]])
LSM:Register("sound", "|cFFa2fff9НаТанкеЧетыреСтака", [[Interface\Addons\EmityCore\sound\ValionaTankFourStacks.mp3]])
LSM:Register("sound", "|cFFa2fff9НаТебеДебаф", [[Interface\Addons\EmityCore\sound\DebuffOnYou.mp3]])
LSM:Register("sound", "|cFFa2fff9Нова", [[Interface\Addons\EmityCore\sound\Nowa.mp3]])
LSM:Register("sound", "|cFFa2fff9Отбеги", [[Interface\Addons\EmityCore\sound\GoAway.mp3]])
LSM:Register("sound", "|cFFa2fff9Отвернись", [[Interface\Addons\EmityCore\sound\FaceAway.mp3]])
LSM:Register("sound", "|cFFa2fff9ОтвернисьЧерезТриДваОдин", [[Interface\Addons\EmityCore\sound\ChogalFaceAwayCount.mp3]])
LSM:Register("sound", "|cFFa2fff9Откидка", [[Interface\Addons\EmityCore\sound\Knockback.mp3]])
LSM:Register("sound", "|cFFa2fff9ОткидкаЧерезТриДваОдин", [[Interface\Addons\EmityCore\sound\AlakirKnockbackCount.mp3]])
LSM:Register("sound", "|cFFa2fff9ОтЛица", [[Interface\Addons\EmityCore\sound\ValionaFromFace.mp3]])
LSM:Register("sound", "|cFFa2fff9ОтсчетБезГолоса", [[Interface\Addons\EmityCore\sound\CountNoVoice.mp3]])
LSM:Register("sound", "|cFFa2fff9ОтсчетСГолосом", [[Interface\Addons\EmityCore\sound\CountdownTenOne.mp3]])
LSM:Register("sound", "|cFFa2fff9Паразит", [[Interface\Addons\EmityCore\sound\Parasite.mp3]])
LSM:Register("sound", "|cFFa2fff9Паучата", [[Interface\Addons\EmityCore\sound\Spiders.mp3]])
LSM:Register("sound", "|cFFa2fff9ПерваяФаза", [[Interface\Addons\EmityCore\sound\FirstPhase.mp3]])
LSM:Register("sound", "|cFFa2fff9ПервыеТкачи", [[Interface\Addons\EmityCore\sound\FirstSpinners.mp3]])
LSM:Register("sound", "|cFFa2fff9ПервыйВзрыв", [[Interface\Addons\EmityCore\sound\FirstBang.mp3]])
LSM:Register("sound", "|cFFa2fff9Перья", [[Interface\Addons\EmityCore\sound\Feathers.mp3]])
LSM:Register("sound", "|cFFa2fff9Пламя", [[Interface\Addons\EmityCore\sound\Fire.mp3]])
LSM:Register("sound", "|cFFa2fff9ПочистисьВОгне", [[Interface\Addons\EmityCore\sound\CouncilWet.mp3]])
LSM:Register("sound", "|cFFa2fff9ПоявиласьЗеленаяЛужа", [[Interface\Addons\EmityCore\sound\GreenPoolAppear.mp3]])
LSM:Register("sound", "|cFFa2fff9ПоявиласьСиняяЛужа", [[Interface\Addons\EmityCore\sound\BluePoolAppear.mp3]])
LSM:Register("sound", "|cFFa2fff9ПоявилисьЧерви", [[Interface\Addons\EmityCore\sound\WormsSpawn.mp3]])
LSM:Register("sound", "|cFFa2fff9ПоявилсяБес", [[Interface\Addons\EmityCore\sound\AtramedesImp.mp3]])
LSM:Register("sound", "|cFFa2fff9ПоявилсяБуревик", [[Interface\Addons\EmityCore\sound\AlakirStormler.mp3]])
LSM:Register("sound", "|cFFa2fff9ПоявляетсяКорхом", [[Interface\Addons\EmityCore\sound\KorhomAppear.mp3]])
LSM:Register("sound", "|cFFa2fff9ПоявляетсяСфера", [[Interface\Addons\EmityCore\sound\CouncilSphereApiar.mp3]])
LSM:Register("sound", "|cFFa2fff9ПоявляютсяАдды", [[Interface\Addons\EmityCore\sound\ChogallAddsSpawn.mp3]])
LSM:Register("sound", "|cFFa2fff9Право", [[Interface\Addons\EmityCore\sound\Right.mp3]])
LSM:Register("sound", "|cFFa2fff9ПробитьЩит", [[Interface\Addons\EmityCore\sound\CouncilShield.mp3]])
LSM:Register("sound", "|cFFa2fff9Прокалывание", [[Interface\Addons\EmityCore\sound\Impale.mp3]])
LSM:Register("sound", "|cFFa2fff9ПрошелКаст", [[Interface\Addons\EmityCore\sound\SinestraCastPassed.mp3]])
LSM:Register("sound", "|cFFa2fff9ПрыгайВЛаву", [[Interface\Addons\EmityCore\sound\NefarianJumpToLava.mp3]])
LSM:Register("sound", "|cFFa2fff9Прячься", [[Interface\Addons\EmityCore\sound\Hide.mp3]])
LSM:Register("sound", "|cFFa2fff9Разрушение", [[Interface\Addons\EmityCore\sound\Destruction.mp3]])
LSM:Register("sound", "|cFFa2fff9РазрушениеПрыгайВниз", [[Interface\Addons\EmityCore\sound\DestructionJumpDown.mp3]])
LSM:Register("sound", "|cFFa2fff9РевЧерезТриДваОдин", [[Interface\Addons\EmityCore\sound\HalfusRoarCount.mp3]])
LSM:Register("sound", "|cFFa2fff9РенжОткидка", [[Interface\Addons\EmityCore\sound\RangeTilt.mp3]])
LSM:Register("sound", "|cFFa2fff9СаперПоявился", [[Interface\Addons\EmityCore\sound\SupperAppear.mp3]])
LSM:Register("sound", "|cFFa2fff9Сбегись", [[Interface\Addons\EmityCore\sound\YouStack.mp3]])
LSM:Register("sound", "|cFFa2fff9СбегисьСГромом", [[Interface\Addons\EmityCore\sound\CouncilStackWithThunder.mp3]])
LSM:Register("sound", "|cFFa2fff9СбегисьСЯдром", [[Interface\Addons\EmityCore\sound\CouncilStackWithGround.mp3]])
LSM:Register("sound", "|cFFa2fff9Сбежаться", [[Interface\Addons\EmityCore\sound\Stack.mp3]])
LSM:Register("sound", "|cFFa2fff9СбросьСтаки", [[Interface\Addons\EmityCore\sound\AlakirLoseStacks.mp3]])
LSM:Register("sound", "|cFFa2fff9Свич", [[Interface\Addons\EmityCore\sound\Switch.mp3]])
LSM:Register("sound", "|cFFa2fff9СвичВЯйца", [[Interface\Addons\EmityCore\sound\SinestraSwitchToEggs.mp3]])
LSM:Register("sound", "|cFFa2fff9Семена", [[Interface\Addons\EmityCore\sound\Seeds.mp3]])
LSM:Register("sound", "|cFFa2fff9СинийБаф", [[Interface\Addons\EmityCore\sound\BlueBuff.mp3]])
LSM:Register("sound", "|cFFa2fff9СиняяФаза", [[Interface\Addons\EmityCore\sound\MaloriakBluePhasse.mp3]])
LSM:Register("sound", "|cFFa2fff9Скинул", [[Interface\Addons\EmityCore\sound\Droped.mp3]])
LSM:Register("sound", "|cFFa2fff9Скоро", [[Interface\Addons\EmityCore\sound\Soon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороАдды", [[Interface\Addons\EmityCore\sound\AddsSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороБерсерк", [[Interface\Addons\EmityCore\sound\BerserkSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороБуря", [[Interface\Addons\EmityCore\sound\StormSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороВолна", [[Interface\Addons\EmityCore\sound\WaveSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороДебафы", [[Interface\Addons\EmityCore\sound\DebuffsSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороДыхание", [[Interface\Addons\EmityCore\sound\BreathSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороИскры", [[Interface\Addons\EmityCore\sound\NefarianLightningSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороКровь", [[Interface\Addons\EmityCore\sound\BloodSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороЛужа", [[Interface\Addons\EmityCore\sound\PoolSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороНова", [[Interface\Addons\EmityCore\sound\CouncilNowaSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороПаразит", [[Interface\Addons\EmityCore\sound\ParasiteSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороПеревод", [[Interface\Addons\EmityCore\sound\PhaseSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороПрокалывание", [[Interface\Addons\EmityCore\sound\ImpaleSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороРев", [[Interface\Addons\EmityCore\sound\HalfusRoarSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороСпарка", [[Interface\Addons\EmityCore\sound\NefarianSparkSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороСтрела", [[Interface\Addons\EmityCore\sound\BoltSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороСтяжка", [[Interface\Addons\EmityCore\sound\VortexSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороСумерки", [[Interface\Addons\EmityCore\sound\TwilightSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороТанцы", [[Interface\Addons\EmityCore\sound\DanceSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороТентакли", [[Interface\Addons\EmityCore\sound\TentaclesSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороТопот", [[Interface\Addons\EmityCore\sound\StompSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороУдарИВолны", [[Interface\Addons\EmityCore\sound\PunchAndWavesSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороФазаБури", [[Interface\Addons\EmityCore\sound\StormPhaseSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороФазаГрозы", [[Interface\Addons\EmityCore\sound\LightingPhaseSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороФрагменты", [[Interface\Addons\EmityCore\sound\PhragmentsSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9СкороЩит", [[Interface\Addons\EmityCore\sound\ShieldSoon.mp3]])
LSM:Register("sound", "|cFFa2fff9Слизь", [[Interface\Addons\EmityCore\sound\ChogalBlood.mp3]])
LSM:Register("sound", "|cFFa2fff9СменаТанков", [[Interface\Addons\EmityCore\sound\ChogalTankChange.mp3]])
LSM:Register("sound", "|cFFa2fff9Сокрушение", [[Interface\Addons\EmityCore\sound\Crash.mp3]])
LSM:Register("sound", "|cFFa2fff9СокрушениеГотовьтесьЗапрыгивать", [[Interface\Addons\EmityCore\sound\MagmawCrashPrepare.mp3]])
LSM:Register("sound", "|cFFa2fff9СокрушениеЧерезТриДваОдин", [[Interface\Addons\EmityCore\sound\MagmawCrashCount.mp3]])
LSM:Register("sound", "|cFFa2fff9СпаркаЧерезТриДваОдин", [[Interface\Addons\EmityCore\sound\NefarianSparkCount.mp3]])
LSM:Register("sound", "|cFFa2fff9СпелСтил", [[Interface\Addons\EmityCore\sound\SpellSteal.mp3]])
LSM:Register("sound", "|cFFa2fff9Спред", [[Interface\Addons\EmityCore\sound\Spread.mp3]])
LSM:Register("sound", "|cFFa2fff9СтойВЦентре", [[Interface\Addons\EmityCore\sound\StayCenter.mp3]])
LSM:Register("sound", "|cFFa2fff9СтопКаст", [[Interface\Addons\EmityCore\sound\StopCast.mp3]])
LSM:Register("sound", "|cFFa2fff9Стрела", [[Interface\Addons\EmityCore\sound\Bolt.mp3]])
LSM:Register("sound", "|cFFa2fff9Стяжка", [[Interface\Addons\EmityCore\sound\Vortex.mp3]])
LSM:Register("sound", "|cFFa2fff9СульфурасЗаряжается", [[Interface\Addons\EmityCore\sound\SulfurasCharge.mp3]])
LSM:Register("sound", "|cFFa2fff9Сумерки", [[Interface\Addons\EmityCore\sound\Twilight.mp3]])
LSM:Register("sound", "|cFFa2fff9Сферы", [[Interface\Addons\EmityCore\sound\SinestraSphers.mp3]])
LSM:Register("sound", "|cFFa2fff9ТанкоБаф", [[Interface\Addons\EmityCore\sound\TanksBuff.mp3]])
LSM:Register("sound", "|cFFa2fff9ТанкПоднялся", [[Interface\Addons\EmityCore\sound\TankUP.mp3]])
LSM:Register("sound", "|cFFa2fff9Танцы", [[Interface\Addons\EmityCore\sound\Dance.mp3]])
LSM:Register("sound", "|cFFa2fff9Таунт", [[Interface\Addons\EmityCore\sound\Taunt.mp3]])
LSM:Register("sound", "|cFFa2fff9Тентакли", [[Interface\Addons\EmityCore\sound\Tentacles.mp3]])
LSM:Register("sound", "|cFFa2fff9Ткачи", [[Interface\Addons\EmityCore\sound\Weavers.mp3]])
LSM:Register("sound", "|cFFa2fff9Токситрон", [[Interface\Addons\EmityCore\sound\OmnitronToxitron.mp3]])
LSM:Register("sound", "|cFFa2fff9Топот", [[Interface\Addons\EmityCore\sound\Stomp.mp3]])
LSM:Register("sound", "|cFFa2fff9Торнадо", [[Interface\Addons\EmityCore\sound\Tornado.mp3]])
LSM:Register("sound", "|cFFa2fff9Третий", [[Interface\Addons\EmityCore\sound\Third.mp3]])
LSM:Register("sound", "|cFFa2fff9ТретьиТкачи", [[Interface\Addons\EmityCore\sound\ThirdSpinners.mp3]])
LSM:Register("sound", "|cFFa2fff9ТретьяФаза", [[Interface\Addons\EmityCore\sound\ThirdPhase.mp3]])
LSM:Register("sound", "|cFFa2fff9ТриДваОдин", [[Interface\Addons\EmityCore\sound\CountThreeTwoOne.mp3]])
LSM:Register("sound", "|cFFa2fff9Трутень", [[Interface\Addons\EmityCore\sound\Drone.mp3]])
LSM:Register("sound", "|cFFa2fff9ТыВЛуже", [[Interface\Addons\EmityCore\sound\YouAreInPool.mp3]])
LSM:Register("sound", "|cFFa2fff9ТыГоришь", [[Interface\Addons\EmityCore\sound\YouAreInFire.mp3]])
LSM:Register("sound", "|cFFa2fff9УвернисьОтВетра", [[Interface\Addons\EmityCore\sound\ConclaveWind.mp3]])
LSM:Register("sound", "|cFFa2fff9Уворачивайся", [[Interface\Addons\EmityCore\sound\Dodge.mp3]])
LSM:Register("sound", "|cFFa2fff9УдарИВолны", [[Interface\Addons\EmityCore\sound\PunchAndWaves.mp3]])
LSM:Register("sound", "|cFFa2fff9ФазаБури", [[Interface\Addons\EmityCore\sound\StormPhase.mp3]])
LSM:Register("sound", "|cFFa2fff9ФазаГрозы", [[Interface\Addons\EmityCore\sound\LightingPhase.mp3]])
LSM:Register("sound", "|cFFa2fff9Фир", [[Interface\Addons\EmityCore\sound\Fear.mp3]])
LSM:Register("sound", "|cFFa2fff9Фрагменты", [[Interface\Addons\EmityCore\sound\Phragments.mp3]])
LSM:Register("sound", "|cFFa2fff9ХилПоднялся", [[Interface\Addons\EmityCore\sound\HealUP.mp3]])
LSM:Register("sound", "|cFFa2fff9ХилТанка", [[Interface\Addons\EmityCore\sound\HealTank.mp3]])
LSM:Register("sound", "|cFFa2fff9Циклон", [[Interface\Addons\EmityCore\sound\Cyclone.mp3]])
LSM:Register("sound", "|cFFa2fff9Чаротрон", [[Interface\Addons\EmityCore\sound\OmnitronCharotron.mp3]])
LSM:Register("sound", "|cFFa2fff9ЧернаяФаза", [[Interface\Addons\EmityCore\sound\MaloriakBlackPhase.mp3]])
LSM:Register("sound", "|cFFa2fff9ЧетвертаяФаза", [[Interface\Addons\EmityCore\sound\PhsaeFour.mp3]])
LSM:Register("sound", "|cFFa2fff9Шары", [[Interface\Addons\EmityCore\sound\Balls.mp3]])
LSM:Register("sound", "|cFFa2fff9ШипВТебя", [[Interface\Addons\EmityCore\sound\ChogalCrashOnYou.mp3]])
LSM:Register("sound", "|cFFa2fff9Щит", [[Interface\Addons\EmityCore\sound\Shield.mp3]])
LSM:Register("sound", "|cFFa2fff9ЩитСнят", [[Interface\Addons\EmityCore\sound\ShieldRemoved.mp3]])
LSM:Register("sound", "|cFFa2fff9ЩупальцаПоявляются", [[Interface\Addons\EmityCore\sound\TentacleAppear.mp3]])
LSM:Register("sound", "|cFFa2fff9Электрон", [[Interface\Addons\EmityCore\sound\OmnitronElectron.mp3]])